spring.application.name=pokedex-rag

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
gemini.api.key=${GEMINI_API_KEY}
gemini.chat.model=${GEMINI_CHAT_MODEL:gemini-flash-lite-latest}
app.ingest.enabled=${APP_INGEST_ENABLED:false}
